### ISSUE TITLE
Enhancement: Convenience method to emit something without consuming input

### ISSUE THREAD

**Issue by mjayfrancis** [python-parsy/parsy#20]
A couple of times I've found myself wanting a builtin method that produces some output without consuming input when none of a set of other possibilities apply; along the lines of:

`some_parser.or_else(my_default_value)`

(Following this thinking, the recently added `optional()` parser method could be thought of as `some_parser.or_else(None)`)

In the absence of a compact notation for this, I have used a function like
```
def emit(content):
    return seq().result(content)
```
which can be used as `some_parser | emit(my_default_value)`. However, abusing seq() like that seems a little inelegant/non-obvious – though I don't mind the interface as an alternative for the same thing

Alternatives include using e.g. a lambda or `functools.partial()` together with `combine()` etc., but when I try this it always seems to end up less legible overall.

Could this be worth building into parsy?

**Comment by bugaevc** [comment]
Maybe I'm missing something, but how would `emit()` be different from the existing `success()`?

**Comment by mjayfrancis** [comment]
You're not missing something, I missed the definition of `success()` :)

So there's already an obvious way to do this, I just overlooked it

**Comment by spookylukey** [comment]
@mjayfrancis if you think the docs for this could be improved in any way, please do let us know!
