### ISSUE TITLE
Examples in tutorial don't quite work exactly as given

### ISSUE THREAD

**Issue by anentropic** [python-parsy/parsy#22]
http://parsy.readthedocs.io/en/latest/tutorial.html

> ```python
> optional_dash = dash.at_most(1)
> 
> @generate
> def full_or_partial_date():
>     d = None
>     m = None
>     y = yield year
>     dash1 = yield optional_dash
>     if len(dash1) > 0:
>         m = yield month
>         dash2 = yield optional_dash
>         if len(dash2) > 0:
>              d = yield day
>     if m is not None:
>        if m < 1 or m > 12:
>            return fail("month must be in 1..12")
>     if d is not None:
>        try:
>            datetime.date(y, m, d)
>        except ValueError as e:
>            return fail(e.args[0])
> 
>     return (y, m, d)
> ```
> 
> This works now works as expected:
> 
> ```
> >>> full_or_partial_date('2017-02')
> (2017, 2, None)
> >>> full_or_partial_date('2017-02-29')
> ParseError: expected 'day is out of range for month' at 0:10
> ```

But if you copy and paste this and run it you get:

```
TypeError: __call__() missing 1 required positional argument: 'index'
```

I was a bit worried at first but I thought I'd just guess that maybe when they're called from a parse method they receive the current index:

```
 >>> full_or_partial_date('2017-02', 0)
 (2017, 2, None)
```

works, as does:
```
>>> full_or_partial_date.parse('2017-02')
 (2017, 2, None)
```

A slight speed bump for beginners :)

**Comment by spookylukey** [comment]
Thanks for reporting, it is missing the `.parse` method call.
