### ISSUE TITLE
alt operator : alt(A, B) != alt(B, A) ?  

### ISSUE THREAD

**Issue by thlabbe** [python-parsy/parsy#24]
Hello, 
Maybe I missed something : 

```
from parsy import *
parse_level_docstring= '''
    Level-numbers: 01-49,66,77,88.
    Each word must be a 1-digit or 2-digit integer.
    '''
@generate(parse_level_docstring)
def level_specials():
    return (yield regex(r'(66|77|88)'))

@generate(parse_level_docstring)
def level_normal():
    level = ( yield regex(r'[0-4]?[0-9]') )
    return level

```
with :
```
@generate(parse_level_docstring)
def level_num():
    level =  yield ( alt (level_normal , level_specials )   )
    return level

```
level_num.parse('88') : **KO** 88, should be OK
level_num.parse('10') : **OK**
level_num.parse('55') : **KO**

with :
```
@generate(parse_level_docstring)
def level_num():
    level =  yield ( alt (level_specials, level_normal  )   )
    return level

```
level_num.parse('88') : **OK** 
level_num.parse('10') : **OK**
level_num.parse('55') : **KO**

**Comment by spookylukey** [comment]
Yes, this is correct, and the documented behaviour - http://parsy.readthedocs.io/en/latest/ref/methods_and_combinators.html#parsy.alt - the parsers are done in order, and it moves to the next only if the first fails, therefore `alt(A, B) != alt(B, A)`

In your case, `level_normal` succeeds at parsing (some of) `88`:

    >>> re.search(r'[0-4]?[0-9]', '88')
    <_sre.SRE_Match object; span=(0, 1), match='8'>

There is also a section in the tutorial about alternatives and backtracking - http://parsy.readthedocs.io/en/latest/tutorial.html#alternatives-and-backtracking 

I will see if I can make the docs for `alt` a bit clearer on this front.

**Comment by spookylukey** [comment]
BTW, you can make your code more succinct like this:

    level_normal = regex(r'[0-4]?[0-9]')
    level_specials = regex(r'(66|77|88)')
    level_num = (level_specials | level_normal).desc(parse_level_docstring)
    # OR:
    level_num = alt(level_specials, level_normal).desc(parse_level_docstring)

(That is, for your case you don't need the `generate` calls).

**Comment by thlabbe** [comment]
OK, that is clearly documented and explained on http://parsy.readthedocs.io/en/latest/tutorial.html#alternatives-and-backtracking 

As I am combining parsers the way I would build a regexp, it's still a bit counter-intuitive to me.

Thank you @spookylukey
