### ISSUE TITLE
Operator for seq()

### ISSUE THREAD

**Issue by tomyun** [python-parsy/parsy#27]
I don't know if it was already discussed, but it'd be nice if we have a shorthand operator (i.e. `&`) for `seq()` which happens to show up quite often in the grammar.

```
class Parser(object):
    ...
    def __and__(self, other):
        return seq(self, other)
```

I guess something like this should simply implement one.

Seems like other parser combinators often have one already:

- `&` for [parsita](https://github.com/drhagen/parsita)
- `>>`/`&&` for [parsnip](http://parsnip-parser.sourceforge.net/)
- `+` for [PaserCombinator.jl](https://github.com/andrewcooke/ParserCombinator.jl)

**Comment by spookylukey** [comment]
Yep, looks like a good suggestion, I'd accept a PR for this. Tests and docs would be needed. Thanks!
