### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by blarghmatey** [python-parsy/parsy#32]
There have been some new capabilities added to the project since the November 2017 release. Are there any plans to cut a new release that is more recent?

**Comment by spookylukey** [comment]
Wish granted! I think you happened to file this just before I noticed the same thing and did a release. v1.3.0 is now on PyPI.

**Comment by blarghmatey** [comment]
Awesome, thank you!

Regards,
Tobias Macey
https://linkedin.com/in/tmacey
