### ISSUE TITLE
Missing documentation for eof parser?

### ISSUE THREAD

**Issue by ijks** [python-parsy/parsy#37]
First off, I want to say I am blown away by how thorough and well-written the docs for this library are. :)

That said, it seems the API reference is missing an entry for [eof](https://github.com/python-parsy/parsy/blob/28d28ec331dc966501cd4932d92c921ff4397608/src/parsy/__init__.py#L457), even though it is used in [this how-to](https://parsy.readthedocs.io/en/latest/howto/lexing.html#turtle-logo). I'm thinking it should have an entry in the "Primitive parsers" section.

I'd be happy to write a PR for this.

**Comment by spookylukey** [comment]
You're right, that seems to be missing, and it should be in "Parsing primitives" as you say. A PR would be much appreciated.

Glad you like the docs :-)
