### ISSUE TITLE
Missing seq import statement in tutorial

### ISSUE THREAD

**Issue by rogerhurwitz** [python-parsy/parsy#50]
I apologize if this is a nit, but in working through the tutorial I noticed the code snippet below left out an import/from statement for the `seq` function before using it.  Explicit imports of `regex` and `string` were included earlier in the tutorial, so I asssume the absence of a similar explict statement for `seq` qualifies as a documentation bug.

![Annotation 2020-09-29 121712](https://user-images.githubusercontent.com/10051773/94605301-c5406080-024d-11eb-9ce2-ab21cbec1371.jpg)

**Comment by spookylukey** [comment]
Thanks for the report, yes we should fix this.
