### ISSUE TITLE
Help with parsing that "hangs"

### ISSUE THREAD

**Issue by sigvaldm** [python-parsy/parsy#52]
Dear community, thanks for the nice library. I am not very familiar with parser combinator libraries yet, but I sometimes encounter expressions that get stuck, such as this one:

```python
>>> spaces = regex(r'[ \t]*')
>>> word = regex('[a-zA-Z0-9\-._:%]*')
>>> words = word.sep_by(spaces)
>>> words.parse('ak kjd l  lksdjf')
```
Any guidance on what I'm doing wrong here? Thank you.

**Comment by bugaevc** [comment]
Your example works if you replace the `*` with a `+` inside the regexes.

When you use a `*`, you're saying that an empty string is a valid `spaces` and also a valid `word`, and so `word.sep_by(spaces)` can have an infinite amount of empty words separated by empty spaces as a prefix.

**Comment by sigvaldm** [comment]
My goodness! I had not thought about that. Thank you. Is there any caveat in leaving `*` in `spaces` but remove it from `word` (i.e. to allow zero or more spaces between them)?

**Comment by sigvaldm** [comment]
Never mind, it would mean that a long word could be parsed as one word per letter, I suppose. In any way, thank you.
