### ISSUE TITLE
Parsy 1.3.0 fails to support 'group' keyword of `regex` function

### ISSUE THREAD

**Issue by mrwizard82d1** [python-parsy/parsy#55]
The following code fails:

```
hms_alt = parsy.regex(r'(\d{2}):', group=(1,))
list(toolz.map(lambda t: hms_alt.parse(t), ['01:', '02:']))
```

The error message is:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-eaea1867982d> in <module>
----> 1 hms_alt = parsy.regex(r'(\d{2}):', group=(1,))
      2 list(toolz.map(lambda t: hms_alt.parse(t), ['01:', '02:']))

TypeError: regex() got an unexpected keyword argument 'group'
```

When I query the signature of the `regex` method, it reports `flags` as a keyword but **not** `group`:

```
parsy.regex?

Signature: parsy.regex(exp, flags=0)
Docstring: <no docstring>
File:      c:\users\larry.jones\appdata\local\pypoetry\cache\virtualenvs\orchid-python-api-_tsnd6qt-py3.8\lib\site-packages\parsy\__init__.py
Type:      function
```

When I look at the source code, I see the following code for `parsy.__init__`:

```
def regex(exp, flags=0):
    if isinstance(exp, str):
        exp = re.compile(exp, flags)

    @Parser
    def regex_parser(stream, index):
        match = exp.match(stream, index)
        if match:
            return Result.success(match.end(), match.group(0))
        else:
            return Result.failure(index, exp.pattern)

    return regex_parser
```

I may not fully understand how everything was implemented but this definition only has the `flags` keyword and **does not** have the `group` keyword.

I am using version 1.3.0 of the package on Windows 10.

Finally, the latest source code in GitHub (`src/parsy/__init__.py`) **does** include the `group` keyword so the cause of the error appears to be in the build process.

**Comment by spookylukey** [comment]
The version number on the docs were in error, sorry for the confusion, should be corrected now.
