### ISSUE TITLE
alt doesn't use fallback parsers when initial parser has .many()/.sep_by()

### ISSUE THREAD

**Issue by nikochiko** [python-parsy/parsy#78]
### Steps to reproduce

```python
>>> p = alt(string("a").many(), string("abc"))
>>> p.parse("abc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../parsy/__init__.py", line 98, in parse
    (result, _) = (self << eof).parse_partial(stream)
  File "/.../parsy/__init__.py", line 112, in parse_partial
    raise ParseError(result.expected, stream, result.furthest)
parsy.ParseError: expected one of 'EOF', 'a' at 0:1
```

The expected output should be `"abc"`.

I'm not sure whether this is intended behaviour or a bug. Intuitively, I would expect the parser to fallback to another parser when the first one fails, without special cases that break this rule.

**Comment by spookylukey** [comment]
This is covered in the tutorial - https://parsy.readthedocs.io/en/latest/tutorial.html#alternatives-and-backtracking and in the docs for https://parsy.readthedocs.io/en/latest/ref/methods_and_combinators.html#parsy.alt , specifically under the docs for https://parsy.readthedocs.io/en/latest/ref/methods_and_combinators.html#parser-or
